# Generated by Django 5.2 on 2026-09-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0022_alter_testcasestep_expected_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='execution_error_message',
            field=models.TextField(blank=True, help_text='最近一次执行失败时的原因说明', null=True, verbose_name='执行失败原因'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='execution_result_data',
            field=models.JSONField(blank=True, help_text='最近一次执行的摘要信息（执行记录ID、耗时、完成时间等）', null=True, verbose_name='执行结果数据'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='execution_status',
            field=models.SmallIntegerField(choices=[(0, '未执行'), (1, '执行中'), (2, '成功'), (3, '失败')], db_index=True, default=0, help_text='最近一次执行结果：0未执行/1执行中/2成功/3失败', verbose_name='执行状态'),
        ),
    ]
