# Generated by Codex on 2026-06-25

from django.conf import settings
from django.db import migrations, models

# SQLite（本地开发）不支持 PostgreSQL 专用的 jsonb/ALTER 语法，
# 此时通过 Django schema 操作添加字段；PostgreSQL 仍使用原生 SQL。
_IS_SQLITE = settings.DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3"

_EXTRACT_META_FIELD = models.JSONField(
    blank=True,
    default=dict,
    help_text='Metadata for extract variable rules',
    verbose_name='Extract Metadata',
)


class Migration(migrations.Migration):

    dependencies = [
        ('api_interfaces', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='apiinterface',
                    name='extract_meta',
                    field=_EXTRACT_META_FIELD,
                ) if _IS_SQLITE else migrations.RunSQL(
                    sql="""
                    ALTER TABLE api_interfaces_apiinterface
                    ADD COLUMN IF NOT EXISTS extract_meta jsonb NOT NULL DEFAULT '{}'::jsonb;

                    UPDATE api_interfaces_apiinterface
                    SET extract_meta = '{}'::jsonb
                    WHERE extract_meta IS NULL;

                    ALTER TABLE api_interfaces_apiinterface
                    ALTER COLUMN extract_meta SET DEFAULT '{}'::jsonb;
                    """,
                    reverse_sql="""
                    ALTER TABLE api_interfaces_apiinterface
                    DROP COLUMN IF EXISTS extract_meta;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='apiinterface',
                    name='extract_meta',
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Metadata for extract variable rules',
                        verbose_name='Extract Metadata',
                    ),
                ),
            ],
        ),
    ]
