# Generated by Codex on 2026-06-25

from django.conf import settings
from django.db import migrations

# SQLite（本地开发）不支持 PostgreSQL 专用的列默认值 ALTER 语法；
# SQLite 的字段默认值由 Django 应用层处理，此迁移仅在 PostgreSQL 上执行。
_IS_SQLITE = settings.DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3"


class Migration(migrations.Migration):

    dependencies = [
        ('api_interfaces', '0003_apiinterface_extract_meta'),
    ]

    operations = [
        migrations.RunSQL(
            sql=migrations.RunSQL.noop if _IS_SQLITE else """
            ALTER TABLE api_interfaces_apiinterface
            ADD COLUMN IF NOT EXISTS extract_meta jsonb NOT NULL DEFAULT '{}'::jsonb;

            UPDATE api_interfaces_apiinterface
            SET extract_meta = '{}'::jsonb
            WHERE extract_meta IS NULL;

            ALTER TABLE api_interfaces_apiinterface
            ALTER COLUMN extract_meta SET DEFAULT '{}'::jsonb;
            """,
            reverse_sql=migrations.RunSQL.noop if _IS_SQLITE else """
            ALTER TABLE api_interfaces_apiinterface
            ALTER COLUMN extract_meta DROP DEFAULT;
            """,
        ),
    ]
